id: P004481
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:25:35.017693
source_metadata:
  id: bdr:W21875
  title: ཟླ་བའི་གོ་ལའི་སླ་གཟུགས་ཀྱི་རྣམ་བཤད།
  author: ''
  volumes:
    8105afe7dbd34a9996084762d83f2dfa:
      image_group_id: I1KG22925
      title: ''
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
