id: P004481
initial_creation_type: ocr
source_metadata:
  id: bdr:W21875
  title: ཟླ་བའི་གོ་ལའི་སླ་གཟུགས་ཀྱི་རྣམ་བཤད།
  author: ''
  volumes:
    8105afe7dbd34a9996084762d83f2dfa:
      image_group_id: I1KG22925
      title: ''
      volume_number: 1
      total_pages: 200
